
#!/bin/bash
#export LD_LIBRARY_PATH=/usr/lib/oracle/12.1/client64/lib
sqlplus64 "dcpatel/06210050@(DESCRIPTION=(ADDRESS=(PROTOCOL=TCP)(Host=oracle.scs.ryerson.ca)(Port=1521))(CONNECT_DATA=(SID=orcl)))" <<EOF
DROP TABLE Actor CASCADE CONSTRAINTS;
DROP TABLE Director CASCADE CONSTRAINTS;
DROP TABLE Producer CASCADE CONSTRAINTS;
DROP TABLE TheUser CASCADE CONSTRAINTS;
DROP TABLE Studio CASCADE CONSTRAINTS;
DROP TABLE Receiver CASCADE CONSTRAINTS;
DROP TABLE Film CASCADE CONSTRAINTS;
DROP TABLE Review CASCADE CONSTRAINTS;
DROP TABLE Awards CASCADE CONSTRAINTS;
DROP TABLE Actor_Acts_In_Film CASCADE CONSTRAINTS;
DROP TABLE Director_Directs_Film CASCADE CONSTRAINTS;
DROP TABLE Producer_Produces_Film CASCADE CONSTRAINTS;
DROP TABLE Studio_Owns_Film CASCADE CONSTRAINTS;
DROP TABLE Awards_Given_To_Film CASCADE CONSTRAINTS;
DROP TABLE TheUser_Creates_Review CASCADE CONSTRAINTS;
DROP TABLE Review_Rates_Film CASCADE CONSTRAINTS;
exit;
EOF
